### PR TITLE
added support for txtpen

### PR DESCRIPTION
**Pull request by rickyhan**

### CODE REVIEW

**Comment by rickyhan** [comment]
txtpen is the only service that provides highlighting and in-text commenting similar to Medium. I think adding txtpen in the official documentation will benefit new Jekyll users and bring web annotation to more people.

Thanks in advance.
Ricky

**Comment by jarrekk** [comment]
Very nice feature, I have a question, when I make a comment at a website which has txtpen but not belong to me, why only me can see this comment? Is there any way to let others see it?

But anyway, I think I will try it. 👍

**Comment by rickyhan** [comment]
Thank you for your kind words. I appreciate it :smile:

To answer your question: on a website that does not have txtpen enabled, everyone can see the posted comment but highlights (without comment) are only visible to the poster.

**Comment by ShashwatHiregoudar** [comment]
Text pen is no longer supported

**Pull request closed without merging**
